# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET
permissions:
  contents: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Set up environment config
      run: |
        echo "{
          \"ConnectionStrings\": {
            \"DefaultConnection\": \"${{ secrets.DB_CONNECTION_STRING }}\"
          }
        }" > programCode/webApi/appsettings.Development.json
    - name: Restore dependencies
      run: dotnet restore programCode/webApi/RestaurantReservierung.sln
    - name: Build
      run: dotnet build programCode/webApi/RestaurantReservierung.sln --no-restore 
    - name: Test
      run: dotnet test programCode/webApi/RestaurantReservierung.sln --no-build --verbosity normal
    - name: Publish
      run: dotnet publish programCode/webApi/RestaurantReservierung.sln -c Release -o publish
    - name: Move files to deployment folder
      run: |
        rm -rf deployment
        mkdir deployment
        cp -r publish/* deployment/
        cp programCode/webApi/bin/Release/net8.0/RestaurantReservierung.dll deployment/RestaurantReservierung.dll
    - name: Commit & push to repo
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add deployment
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Deploy: Add latest build output"
          git push
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
